name: Healthcheck and README

on: push

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
            python-version: '3.13' 
                
      - run: python scripts/healthcheck.py
      - run: python scripts/readme.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update status and readme
        